### ISSUE TITLE
Add more Heroku specific gems

### ISSUE THREAD

**Issue by svlasov** [dennybritz/rails_startup_template#6]
gem 'puma' #Heroku's recommendation is to use Unicorn but Puma is good enough (or even better?) and doesn't require additional configurstion
...
group :production do
  gem "rails_12factor"
  gem 'rails_on_heroku'
  gem 'pg' #probably you should put it into development and test too
end

**Comment by rubiconvvv** [comment]
Good idea, make a Pull Request with that.

**Comment by dennybritz** [comment]
Good idea. It should probably be inside a "Are you using Heroku?" question block. I'll merge the PR if you submit it. If you don't have time to submit one I will do this myself tomorrow.

**Comment by dennybritz** [comment]
I'm gonna close this issue since there's a pull request for it.
