### ISSUE TITLE
Add ability to create github repository

### ISSUE THREAD

**Issue by smoran02** [dennybritz/rails_startup_template#7]
Hi, I've been working on this issue, but having trouble with an error.

Here is the code I added:

``` ruby
# Add github repository
# ==================================================
if yes?("Add github repository?")
  user = [(print 'Github username: '), gets.rstrip][1]
  repo_name = [(print 'Repository name: '), gets.rstrip][1]
  run %Q[curl -u '#{user}' https://api.github.com/user/repos -d '{"name": "#{repo_name}"}']
end
```

And here is the error I get:
Github username: The template [.../rails_startup_template/template.rb] could not be loaded. Error: No such file or directory -- new_app.

If anyone can help me out or take it from here that would be great! Thanks for working on this.

**Comment by rubiconvvv** [comment]
It's problem with gets.rstrip, i'm trying find out.

**Comment by rubiconvvv** [comment]
By the way, you can replace line with user, by run 'git config user.name', and repo_name can retrieve from config/application.rb file

**Comment by smoran02** [comment]
Can I use @app_name for the second part?

**Comment by rubiconvvv** [comment]
Of course, why not.

**Comment by tbpalsulich** [comment]
I put in a pull request to create a remote repo. But, I was having the same could not be loaded issue. Instead of using `gets`, use `ask`. So, `user = ask "What is your Github username?"` I'm not sure exactly why, but the template loader doesn't like gets.

**Comment by rubiconvvv** [comment]
I think, the reason of gets fail in ancestor of Template Object, probably
method gets redefined somewhere, so it template environment it's dont work.

**Comment by smoran02** [comment]
Yep, I just came to post the corrected version, but it's already in another issue. Just merge that one instead. Closing this now.
